#!/usr/bin/env bash
# Configures domain zones and subdomains in A record

domains_info () {
    dig_info=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $dig_info" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
    
}

if [ $# == 2 ]; then
    domains_info $1 $2
elif [ $# == 1 ]; then
    domains_info $1 "www"
    domains_info $1 "lb-01"
    domains_info $1 "web-01"
    domains_info $1 "web-02"
fi