#!/usr/bin/env bash
# Configuring nginx to listen on port 80 - the default port
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
