#!/usr/bin/env bash
# Displays numbers from 1 to 100
# Display FizzBuzz when a number is a multiple of 3 and 5
# Dispay Fizz when a number is multiple of 3
# Display Buzz when a number is multiple of 5

i=1

while (( i<=100 )); do
    if (( i%3 == 0 )) && ((i%5 == 0)); then
	echo FizzBuzz
    elif (( i%3 == 0)); then
	echo "Fizz"
    elif (( i%5 == 0 )); then
	echo "Buzz"
    else
	echo "$i"
    fi
    i=$(( i+1 ))
done
