#!/usr/bin/env bash
# displays the content of /etc/passwd
# only display the username, user id, user home directory path

while read -r line; do
    echo "$line" | cut -d ":" -f1,3,6
done < /etc/passwd
