#!/usr/bin/env bash
# Displays Best School 10 times, and Hi on the 9th interation

i=1

while (( i<=10 )); do
      echo "Best School"
      if (( i==9 )); then
      	 echo "Hi"
      fi
      i=$(( i+1 ))
done
