#!/usr/bin/env bash
# Displays Best School 10 times,
# but bad luck on the 4th iteration, and
# good luck on the 8th iteration

i=1

while (( i<=10)); do
      if (( i!=4 )) && (( i!=8 )); then
      	  echo "Best School"
      elif (( i==4 )); then
	   echo "bad luck"
      else
	  echo "good luck"
      fi
      i=$(( i+1 ))
done
