#!/usr/bin/env bash
# display the time for 12 hours 59 minuntes
# displsy hours from 0 to 12
# dislay minutes from 1 to 59

hour=0

while (( hour<=12 )); do
    echo "Hour: $hour"
    min=1
    while (( min<=59 )); do
	echo "$min"
	min=$(( min+1 ))
    done
    hour=$(( hour+1 ))
done
